COMPILE = g++ -std=c++14

test: 
	$(COMPILE) serialize-test.cpp -o bin/serialize-test
	./bin/serialize-test

tree: 
	$(COMPILE) serialize-tree.cpp -o bin/serialize-tree
	./bin/serialize-tree

$(shell mkdir output)
